# Generated by Django 4.1.7 on 2023-03-08 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ch_id', models.IntegerField(max_length=3)),
                ('ch_name', models.CharField(max_length=150)),
                ('plant_type', models.CharField(max_length=200)),
                ('plant_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlantRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('plant_type', models.CharField(max_length=200)),
                ('moisture_lvl', models.IntegerField(blank=True, max_length=3, null=True)),
                ('temperature_lvl', models.IntegerField(blank=True, max_length=3, null=True)),
                ('humidity_lvl', models.IntegerField(blank=True, max_length=2, null=True)),
                ('light_lvl', models.IntegerField(blank=True, max_length=4, null=True)),
                ('time', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
