# Generated by Django 4.1.7 on 2023-03-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddb', '0002_remove_channeldata_id_alter_channeldata_ch_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_type', models.CharField(max_length=200)),
                ('max_moisture_lvl', models.IntegerField(default=90)),
                ('min_moisture_lvl', models.IntegerField(default=40)),
                ('max_temperature_lvl', models.IntegerField(blank=True, null=True)),
                ('min_temperature_lvl', models.IntegerField(blank=True, null=True)),
                ('max_humidity_lvl', models.IntegerField(blank=True, null=True)),
                ('min_humidity_lvl', models.IntegerField(blank=True, null=True)),
                ('min_light_lvl', models.IntegerField(blank=True, null=True)),
                ('max_light_lvl', models.IntegerField(blank=True, null=True)),
                ('daylight_time', models.IntegerField(blank=True, null=True)),
                ('amount_water', models.IntegerField(blank=True, null=True)),
                ('time_between_watering', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
