# Generated by Django 4.1.7 on 2023-03-08 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddb', '0003_plantdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channeldata',
            old_name='ch_name',
            new_name='ch_number',
        ),
    ]
