# Generated by Django 4.1.7 on 2023-03-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddb', '0004_rename_ch_name_channeldata_ch_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantdb',
            old_name='time_between_watering',
            new_name='hours_between_watering',
        ),
    ]
