# Generated by Django 4.1.7 on 2023-03-08 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddb', '0009_alter_plantrecord_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantrecord',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 21, 29, 53, 129840, tzinfo=datetime.timezone.utc)),
        ),
    ]
