# Generated by Django 4.1.7 on 2023-03-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('auto_mode', models.BooleanField(default=False)),
                ('stats', models.CharField(max_length=2000)),
                ('status', models.CharField(max_length=2000)),
            ],
        ),
    ]
